### ISSUE TITLE
Release on crates.io

### ISSUE THREAD

**Issue by lulf** [embassy-rs/bt-hci#14]
Would be great to release this crate on crates.io, as it would allow HALs/controllers to implement the traits without relying on git dependencies.

I'm happy to do it, but figured maybe you want to be the owner @alexmoon

**Comment by alexmoon** [comment]
I think that's a good idea. The API has been stable for awhile and seems to have been working for you.

Do you think we should move it into the embassy organization, or is it better to keep it independent?

**Comment by lulf** [comment]
That's up to you, I think it could make sense to put it in embassy, as it could help with governance over time. OTOH I don't expect it to change more than bugfixes, small improvements and additions to the standard so :shrug:

**Comment by alexmoon** [comment]
Yeah, governance is what I was thinking about. I don't want to be a bottleneck in the future. Should we check what @dirbaio thinks?

We also need to add a README and a check that we have docs on everything.

**Comment by alexmoon** [comment]
I've published v0.1.0 on crates.io. @lulf I've sent you an owner invite. I'm not sure how to add the embassy team.
