### ISSUE TITLE
Add GattValue and FixedGattValue traits from nrf-softdevice to bt-hci

### ISSUE THREAD

**Issue by petekubiak** [embassy-rs/bt-hci#18]
These traits will be critical for implementing the softdevice-like interface we're developing in TrouBLE (link: https://github.com/embassy-rs/trouble/issues/136), and I imagine would be useful more broadly as well.

**Comment by alexmoon** [comment]
I think these are a host concern rather than an HCI concern, so should probably be in trouble rather than bt-hci. The HCI messages are inherently variable length, it's just the interpretation of that raw data by the host that needs to be aware of type conversions.

**Comment by jamessizeland** [comment]
Fair enough, our thinking was that the conversion traits would be generic beyond trouble, as it's just the same interface as softdevice uses.
