### ISSUE TITLE
Add CI Publish to Crates.io Stage

### ISSUE THREAD

**Issue by ScottGibb** [embassy-rs/bt-hci#20]
Hi All,

Good work on the bt-hci so far. Really interesting project!

I noticed that on https://crates.io/crates/bt-hci/versions we have two tagged releases (v0.1.0 and v0.1.1). However on GitHub we have no tagged releases. I assume at the moment the publishing to Crates.io is done manually.

Im wondering if there's value in us adding a CI Publish stage where we can auto tag and publish using Github actions. How we decide to achieve that can be discussed in this issue and then we can go implement it.

A quick google resulted in the following [guide](https://pratikpc.medium.com/publishing-crates-using-github-actions-165ee67780e1), i'm sure we can come up with something a bit more sophisticated.

**Comment by lulf** [comment]
That would be nice, but this is not a crate that is typically updated very frequently, so I'm not sure if there is any time saved. It would be good to use some helper like `cargo releaser` to ensure tags and other things gets updated though, so thanks for raising the issue.

**Comment by ScottGibb** [comment]
@lulf Ive proposed the work for this and should start working on this and https://github.com/embassy-rs/trouble/issues/154 in the next couple of weeks :)
